### ISSUE TITLE
FYI: errors when installing modules

### ISSUE THREAD

**Issue by customcommander** [yui/selleck#17]
Issued `npm install` as a root (Mac OS X 10.7.5) and got the following output:

```
npm http GET https://registry.npmjs.org/yui-lint
npm http GET https://registry.npmjs.org/jshint
npm http 304 https://registry.npmjs.org/yui-lint
npm http 304 https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/cli/0.4.3
npm http GET https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/jshint
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/cli/0.4.3
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/shelljs
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/peakle
npm http GET https://registry.npmjs.org/cli
npm http GET https://github.com/ariya/esprima/tarball/master
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/minimatch
npm WARN optional dep failed, continuing graceful-fs@^3.0.2
npm http GET https://registry.npmjs.org/minimatch
npm ERR! Error: No compatible version found: minimatch@'^0.3.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.4","0.0.5","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.2.0","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.2.11","0.2.12","0.2.13","0.2.14","0.3.0"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:563:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:478:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/Julien/Github/selleck
npm ERR! node -v v0.8.16
npm ERR! npm -v 1.1.69
npm http 304 https://registry.npmjs.org/shelljs
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/peakle
npm http 304 https://registry.npmjs.org/cli
npm http 200 https://github.com/ariya/esprima/tarball/master
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/graceful-fs
npm WARN optional dep failed, continuing graceful-fs@^3.0.2
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/minimatch
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Julien/Github/selleck/npm-debug.log
npm ERR! not ok code 0
```

I've been able to run `make docs` without any problem.

**Comment by okuryu** [comment]
This is same with https://github.com/yui/yui3/issues/1833.

You need to install latest npm `npm install -g npm` at Node.js 0.8 avoid this issue.

**Comment by customcommander** [comment]
Mmmh weird because I'm running node v0.8.16.

Is there a specific node version to install?

**Comment by caridy** [comment]
npm issue, closing.
